- fail: msg="You must define s3cmd_access_key, s3cmd_secret_key and s3cmd_user"
  when: s3cmd_access_key is not defined or
    s3cmd_secret_key is not defined or
    s3cmd_user is not defined

- name: Install s3cmd
  apt:
    name: ['python-magic', 's3cmd']
    state: latest

- name: Adds s3 credentials
  template: >
    src=../templates/s3cfg.j2
    dest=~{{ s3cmd_user }}/.s3cfg
    owner={{ s3cmd_user }}
    mode=600
